export const showItemList = [
  { _id: "100", title: "Automotive" },
  { _id: "101", title: "Baby" },
  { _id: "102", title: "Beauty & Personal Care" },
  { _id: "103", title: "Books" },
  { _id: "104", title: "Boy's Fashion" },
  { _id: "105", title: "Computers" },
  { _id: "106", title: "Deals" },
  { _id: "106", title: "Mobiles & Laptops" },
  { _id: "107", title: "Digital Electronics" },
  { _id: "107", title: "Electronics" },
  { _id: "107", title: "Girls Fashion" },
  { _id: "107", title: "Health & HouseHold" },
  { _id: "107", title: "Home & Kitchen" },
  { _id: "107", title: "Industrial & Scientific" },
  { _id: "107", title: "Kindle Store" },
  { _id: "107", title: "Lugguage" },
  { _id: "107", title: "Movies & TV" },
];